// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAevnNXT__ar63tHtbqpRcDWqlms50NYYQ',
    appId: '1:895118199775:web:fbc7fb232b95faa03c526a',
    messagingSenderId: '895118199775',
    projectId: 'flutter-cc-evs',
    authDomain: 'flutter-cc-evs.firebaseapp.com',
    storageBucket: 'flutter-cc-evs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEa3ydQqDQRaG1jck7JL1EVEN_N9wHIjM',
    appId: '1:895118199775:android:f2d5fa0b9bed51fc3c526a',
    messagingSenderId: '895118199775',
    projectId: 'flutter-cc-evs',
    storageBucket: 'flutter-cc-evs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYZWx3mSmjqIH-jAXpwVy3cNyIRd7NrLk',
    appId: '1:895118199775:ios:deffdbd5b7b106403c526a',
    messagingSenderId: '895118199775',
    projectId: 'flutter-cc-evs',
    storageBucket: 'flutter-cc-evs.firebasestorage.app',
    iosBundleId: 'com.example.flutterCcEvs',
  );
}
